name: Playwright Tests

on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
      - run: docker compose up server -d --wait
      - run: docker compose run --name playwright-test --no-deps test
      - if: ${{ !cancelled() }}
        run: docker cp playwright-test:/app/playwright-report/. ./playwright-report/
      - if: ${{ !cancelled() }}
        run: docker rm playwright-test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
